server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: "jdbc:mysql://localhost:3306/priceFlow"
    username: "root"
    password: "qwert12345"
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost

message: "second message"
